version: '4'
services:
  keitee-website-admin:
    image: idsteamvn/keitee-website-admin:v1.0.0
    container_name: keitee-website-admin
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-production

    ports:
      - '2203:2203'
    networks:
      - dynasty-dashboard-network

networks:
  dynasty-dashboard-network:
    external: true
