version: '4'

services:
  dynasty-dashboard:
    image: dynasty-dasboard:production
    container_name: dynasty-dashboard
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-production

    ports:
      - 1311:1311
    networks:
      - dynasty-dashboard-network

networks:
  dynasty-dashboard-network:
    external: true
