version: '3.8'

services:
  dynasty-dasboard:
    container_name: dynasty-dashboard
    image: dynasty-dasboard:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1311:1311
