version: '3.8'

services:
  dynasty-dasboard:
    image: tanphamvan/dynasty-dasboard:staging
    container_name: dynasty-dashboard
    build:
      context: .
      dockerfile: Dockerfile-staging
    ports:
      - 1311:1311
    networks:
      - dynasty-dashboard-network

networks:
  dynasty-dashboard-network:
    external: true
